#!/usr/bin/env php
<?php
require dirname(__DIR__) . '/vendor/autoload.php';

use CarlosIO\WhatsApp\Command\SendCommand;
/*
use CarlosIO\WhatsApp\Command\ListenCommand;
use CarlosIO\WhatsApp\Command\InteractiveConversationCommand;
use CarlosIO\WhatsApp\Command\ChangeStatusCommand;
*/
use Symfony\Component\Console\Application;

$send="41763440060";
$imai="013195006205051";
/*
$application->add(new ListenCommand);
$application->add(new InteractiveConversationCommand);
$application->add(new ChangeStatusCommand);
*/
$php whatsapp.php -i 41794666600;
